# Generated by Django 3.2.22 on 2023-11-01 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_image_home_imagehome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='imagehome',
            new_name='cover',
        ),
    ]
