# Generated by Django 4.2.7 on 2023-11-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_imagehome_home_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="subtitle",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
