# Generated by Django 4.2.7 on 2023-11-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_home_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
