# Generated by Django 4.2.7 on 2023-11-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_album_coveralbum"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="thumbnai",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
