# Generated by Django 4.2.7 on 2023-11-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_image_thumbnai"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="album",
        ),
        migrations.AddField(
            model_name="image",
            name="album",
            field=models.ManyToManyField(related_name="images", to="core.album"),
        ),
    ]
