# Generated by Django 4.0.4 on 2023-11-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_image_album_image_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='picture',
        ),
    ]
