# Generated by Django 4.0.4 on 2023-11-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_image_image_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='name',
        ),
    ]
