# Generated by Django 4.0.4 on 2023-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_thumbnai_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='coveralbum',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cover',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='media/'),
        ),
    ]
