# Generated by Django 4.0.4 on 2023-12-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_album_coveralbum_alter_home_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.FileField(upload_to='media/'),
        ),
    ]
