# Generated by Django 4.0.4 on 2024-01-02 12:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_image_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='coveralbum',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to='media/'),
        ),
    ]
