# Generated by Django 4.0.4 on 2024-01-02 12:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_album_coveralbum_alter_home_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='coveralbum',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[300, 300], upload_to='media/'),
        ),
    ]
