# Generated by Django 4.0.4 on 2024-01-02 13:03

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_album_coveralbum_alter_image_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[350, 400], upload_to='media/'),
        ),
    ]
