# Generated by Django 4.0.4 on 2024-01-02 14:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='media/'),
        ),
    ]
