# Generated by Django 4.0.4 on 2024-01-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_image_picture_alter_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='album',
        ),
    ]
