# Generated by Django 4.0.4 on 2024-01-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
